name: neat-sandbox 
services:
  ubuntu:
    type: compose
    app_mount: delegated
    services:
       command: sleep infinity 
       build:
         context: .
         dockerfile: Dockerfile
       environment:
         DISPLAY: :0
         PHP_IDE_CONFIG: "serverName=neat-sandbox"
         XDEBUG_MODE: debug
         XDEBUG_SESSION: 1
         LD_LIBRARY_PATH: /usr/local/lib 
         # https://askubuntu.com/questions/170668/intel-do-flush-locked-failed-input-output-error
         LIBGL_ALWAYS_SOFTWARE: 1
       volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
tooling:
  php:
    service: ubuntu 
    cmd:
      - "php"

